use_multiprocessing: true  
n_workers: 8        # Number of parallel workers 
stop_on_multiprocessing_fail: true

# Memory management settings
memory_management:
  monitor_memory: false
  batch_size: 10
  aggressive_gc: true

# Data generation settings  
num_data: 20        # number of images to generate
seed: 7499

# VARIABLE PSF setting
variable_psf: true
variation_factor: 1.0
save_psf_param: true

# FIXED PSF setting
psf_type: "moffat"          # "moffat" or "gauss"
morph: 'exp'                

# other setting
mag: 17.0                   # 17.0 is default
hlr: 0.5                    # 0.5 is default
pixel_scale: 0.2            # 0.2 is default
layout_name: 'random'       # 'random' or 'grid'
coadd_dim: 2550             # without rotation, image dim is coadd_dim + 1
buff: 0                     # 0 is default
sep: 9.5                    # null is default
bands: ['r', 'i', 'z']      # ['i'] is default
noise_factor: 1             # 0.58 is default
dither: False               # False is default
dither_size: 0.5            # 0.5 is default
rotate: False               # False is default
cosmic_rays: True          
bad_columns: True       
shear_setting: vary       # vary or const

density: 10                 # GALAXY density: per square arcmin, 80 is default  

setting: test

catalog_type: 'wldeblend'   # 'wldeblend' or 'fixed'   
select_observable: 'i_ab'   # column name in the WLDEBlend catalog
select_lower_limit: null
select_upper_limit: 27 
n_tiles_per_side: 1

# Star configuration
generate_star: true # set to false to disable star catalog
star_bleeds: true 

star_config:
  # max_density: 100 
  density: 10 

star_setting:
  star_filter: true
  star_filter_mag: 18.0
  star_filter_band: 'r'

draw_bright: false
